### ISSUE TITLE
Typo on Spring Day 4?

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#1]
I was going to submit a PR for this paragraph but then realized I didn't actually know what that first sentence was trying to say so thought I'd just file an issue. 

Traveling to the mailbox via the Backwoods and vice versa is nearly 20 minutes faster than via Pelican Town. Likewise, traveling to the mailbox from The Mines and vice versa via the Backwoods is faster.

**Comment by nathan-alden-sr** [comment]
Thanks for the feedback. I hope [this change](https://github.com/nathan-alden-sr/stardew-valley/commit/26482137b1d1fd524c6f8fa8ebd5d13b3fc1ead8#diff-3be58915d10995a97a8f3f1e1939256fdfef332b5920002a2a124355919263bcR18) has made the language unambiguous.

**Comment by waynn** [comment]
It does, although I liked your phrasing before to make it clear that the
timing was to the mailbox rather than just to the Farm.

Looking forward to the rest of the guide coming up!
