### ISSUE TITLE
Spreadsheeet not working in Google Sheets

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#14]
I've been importing the spreadsheet to Google Sheets so that I can keep track across two computers and my phone, but Sp5 doesn't work on the latest version (I actually had to go back 7 days to the April 28th version to get it to work). I'm not sure if it's important to you, but the new cells for calculating Parsnip XP don't seem to work. I'll use the old version for now but wanted to create an issue in case you cared/didn't know.

**Comment by nathan-alden-sr** [comment]
I see what happened. I actually maintain two versions of the spreadsheet: one in the repo that is reset to default, and one on my desktop that I use for my own runs. I usually change my copy first, verify everything's good, then copy the cells to the repo's version. Unfortunately, Calc tried to be intelligent about this and generated local paths in the spreadsheet.

I'll fix them and push an update shortly.

**Comment by nathan-alden-sr** [comment]
https://github.com/nathan-alden-sr/stardew-valley/commit/27fa3e2d4d4c0ca120b66f0a6a50919654992b8f
