### ISSUE TITLE
Spreadsheet Sp5 has data in it

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#16]
Not a big deal but there's data in the Parsnips Harvested cell already.

Unrelated, I did find the "Coal Needed" a little confusing because I didn't realize it included the 5 you need for Copper already.

**Comment by nathan-alden-sr** [comment]
Fixed both of these. Thank you. 👍

https://github.com/nathan-alden-sr/stardew-valley/commit/13f274ea1d19acb17fdae1d9d809e7edba166493
https://github.com/nathan-alden-sr/stardew-valley/commit/d37df3acb2f31a5a6d9c3c238dbf3d2e7a7de9d7
