### ISSUE TITLE
No Y1-Sp8 Tab?

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#19]

**Comment by nathan-alden-sr** [comment]
Back when I first designed the spreadsheet, I didn't have the *Generic Item Table* tab. I was noticing that many daily tabs are the same: an item list, a G target, etc. Quite some time ago I removed all the redundant tabs in favor of the single generic tab. However, you are free to duplicate the tab and use it per-day if you wish. I just want to keep the spreadsheet in source control simple.
