### ISSUE TITLE
Y1-Sp10 Tab

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#20]
1. Parsnip XP should probably be Potato XP, but also should add a row for Parsnip/Parsnip XP?
2. You specify irrigated vs unirrigated Rice but I don't think it matters from an XP perspective?

**Comment by nathan-alden-sr** [comment]
I'm about to push a significant change to the spreadsheet. Hang on.

**Comment by nathan-alden-sr** [comment]
I pushed a bunch of changes that affect multiple tabs. See the new advice in [Spring 1](https://github.com/nathan-alden-sr/stardew-valley/blob/master/min-max/1.5/year-1-spring-1.md#advice-and-warnings). This change affected the various daily tabs that previously were calculating lots of Farming XP stuff. Now those tabs just pull experience values from the new *Y1-Sp Faming XP Planning* tab.

I've been meaning to make this change for quite some time as the unpredictable planting of Mixed Seeds and Irrigated Rice Shoots made the process annoying. Let me know if my changes are understandable.

**Comment by waynn** [comment]
Hm that makes sense, but then where are you putting the Rice Shoots? I
don't see that on the SP Farming XP Planning tab?

**Comment by waynn** [comment]
I just copied the lines further down and added rice and looks like it works
as expected :+1:

**Comment by nathan-alden-sr** [comment]
Yep, as long as you remember to copy the hidden cells (LibreOffice doesn't make that easy) you can add as many rows as you want, and they can be duplicates.
