### ISSUE TITLE
Spring 16

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#24]
`This is the last day you can craft the remaining required Sprinklers. Any later than today and the second Kale crop will not mature in time.`

I never quite understood what this meant even in the original guide, because aren't you watering the plants that aren't getting hit by Sprinklers? So why is this the last day?

**Comment by nathan-alden-sr** [comment]
You're right, of course. I've removed this.

https://github.com/nathan-alden-sr/stardew-valley/commit/c254f6a4a1f14cc169f3cd15c4d0337db9b944ea
