### ISSUE TITLE
Mushrooms in Cave

### ISSUE THREAD

**Issue by waynn** [nathan-alden-sr/stardew-valley#4]
They actually regenerate daily, not every two days just as a heads-up.

**Comment by waynn** [comment]
I'm going to close this for now because everything I've found still says 1-2 days, but I gathered mushrooms three days in a row in the morning before going to the mines so I'm confused now. Will screenshot it next time.

**Comment by waynn** [comment]
Posted this in Zamiell's repo also.

Ok, here are five screenshots showing -- I actually missed a day in between, and on Spring 11 the boxes are empty because I just harvested them (you can see the bottom left corner), but I figured I'd upload all of them. So maybe it's different on Switch, but I definitely harvested them 6 days in a row in the morning.



![2021050808573200-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767706-2833a600-b1e6-11eb-8539-65722f4a5d2a.jpg)
![2021050814094900-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767709-2964d300-b1e6-11eb-979a-92d8a82a5970.jpg)
![2021050814584300-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767711-2a960000-b1e6-11eb-9d7c-616fbe5df51b.jpg)
![2021050916104000-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767713-2b2e9680-b1e6-11eb-9248-e162cb7b8a4b.jpg)
![2021051015403100-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767715-2b2e9680-b1e6-11eb-9de8-16179607dc37.jpg)

**Comment by nathan-alden-sr** [comment]
From the wiki:
>Cave mushroom production takes one to two days. Unlike other processing, the time when mushrooms are ready for harvest depends upon the time when the player goes to sleep: processing is faster if the player goes to sleep later.[2] The earliest mushrooms can be ready is 12:40pm, if the player goes to sleep at 2am. If the player goes to sleep at or before 6pm, mushrooms will not be ready until two days later, resulting in a missed day of production. These processing times apply both to newly-placed mushroom boxes and to existing ones that were just harvested.

**Comment by nathan-alden-sr** [comment]
https://github.com/nathan-alden-sr/stardew-valley/commit/f337feede8a6b536c4aecc093868031f3196804a
