### ISSUE TITLE
Spring day 4 minor typo

### ISSUE THREAD

**Issue by jfordxx** [nathan-alden-sr/stardew-valley#45]
In the section where you're 'not purchasing more Bait' it says to chop 150 wood, to use on a scarecrow and a chest. But that only requires 100 wood. Was the extra 50 wood supposed to be used to build a chest on day 5 for the mines?

**Comment by nathan-alden-sr** [comment]
Interesting. It's been awhile since I worked on this, but it appears as though yes, the 150 Wood is for two Chests and one Scarecrow.

**Comment by nathan-alden-sr** [comment]
Fixed. Thanks!

https://github.com/nathan-alden-sr/stardew-valley/commit/a0e2370e09b067de9af01254ddcaec0a2333b579
