### ISSUE TITLE
First pieces of copper

### ISSUE THREAD

**Issue by Pitabread21** [nathan-alden-sr/stardew-valley#47]
Hi, I’m enjoying how thorough this guide is. It’s my first min max run and it’s been a great challenge. 

One issue I was running in to was getting Clint to give me the furnace blue prints on/before day 5. I’m playing on console and mobile. Buying from him wouldn’t trigger his cutscene but was guaranteed when I would find the copper naturally. 

Also, I made more mistakes that caused me to be very tight on time on day 5. I managed to get through by banking on geodes having at least 10 copper ore for me to use. A suggestion if you think it fits with your guide.

**Comment by nathan-alden-sr** [comment]
Hi. I don't really maintain this anymore as I consider it feature-complete. It was designed for the Steam/PC version of the game. It's possible console/mobile versions have slightly different mechanics.
